apiVersion: v1
kind: Service
metadata:
  name: postgre-service
spec:
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: profisearch
    app.kubernetes.io/name: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30032
  type: NodePort
