apiVersion: batch/v1
kind: Job
metadata:
  name: create-table-db-user-job
spec:
  template:
    spec:
      containers:
      - name: create-table-db-user-job
        env:
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: db-user-config
                key: PGDATABASE
          - name: PGUSER
            valueFrom: 
              secretKeyRef:
                name: db-user-secret
                key: PGUSER
          - name: PGPASSWORD
            valueFrom: 
              secretKeyRef:
                name: db-user-secret
                key: PGPASSWORD
          - name: PGHOST
            valueFrom: 
              configMapKeyRef:
                name: db-user-config
                key: PGHOST
          - name: PGPORT
            valueFrom: 
              configMapKeyRef:
                name: db-user-config
                key: PGPORT
        
        image: alekseybondarev/psql:v1
        command: ["psql",  "-c"]
        args:
          - CREATE TABLE IF NOT EXISTS public.users
            (
                id SERIAL PRIMARY KEY,
                user_name varchar(255),
                first_name varchar(255),
                last_name varchar(255),
                email varchar(255),
                phone varchar(255)
            ) TABLESPACE pg_default;

            ALTER TABLE IF EXISTS public.users OWNER to profi;


      restartPolicy: Never
  backoffLimit: 4

