apiVersion: v1
kind: Service
metadata:
  name: db-user-service
  labels:
    app: db
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: db

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-user-statefulset
spec:
  serviceName: "db-user-service"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgredb
        command: 
        
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-user-config
                key: user-db-name
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: db-user-secret
                key: db-user-user
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: db-user-secret
                key: db-user-password
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi